### PR TITLE
[UI] Convert CTA for unit of temperature to Switch widget

### LINKED ISSUE #106: [BUG] Not obvious that F can be changed to C on temperature screen
**Describe the bug**
It is not obvious that F can be changed to C on the temperature screen. Using something like ToggleButtons or a dropdown Button may make it more obvious.

**To Reproduce**
1. Navigate to temperature screen (second screen of checkup)
2. Observe F button

**Screenshots**
Screen Shot 2020-03-24 at 2 43 01 PM

### PR DESCRIPTION
**Pull request by joshuadeguzman**
Fixes #106 

This PR makes it more apparent to the user whether the unit for the temperature is in Celsius or Fahrenheit.

**Demo**

### CODE REVIEW

**Comment by dnfield** [comment]
This now has merge conflicts.  I'm also not sure a `Switch` is the right idiom here - switch is usually for `on/off` properties.

**Comment by joshuadeguzman** [comment]
> This now has merge conflicts. I'm also not sure a Switch is the right idiom here - switch is usually for on/off properties.

Thanks @dnfield for your feedback!

Apologies for the conflict, I think this was started prior the global design changes.

Is the issue still valid based on the new design changes?

Screen Shot 2020-03-27 at 11 31 47 AM

**Comment by ferndot** [comment]
Perhaps, `ToggleButtons` could be used here?

**Comment by joshuadeguzman** [comment]
> Perhaps, ToggleButtons could be used here?

@joshua-s Can, but unsure what are the final decision for this one. I've seen some discussion in the issue ticket that there maybe an alternative UX for this and remove this component instead totally.

Nonetheless, if you're looking for use of `ToggleButtons`, here it is:

**Pull request closed without merging**
