### PR TITLE
[WIP] add codemagic.yaml

### PR DESCRIPTION
**Pull request by christopherfujino**
Re-attempt at https://github.com/coronavirus-diary/coronavirus-diary/pull/66.

### CODE REVIEW

**Comment by christopherfujino** [comment]
@jonahwilliams still no pre-submit on this one either. Is https://codemagic.io/app/5e7baffcda0eac000e5d472c the right app?

**Comment by jonahwilliams** [comment]
I wonder if the config needs to be commited first?

**Comment by christopherfujino** [comment]
> I wonder if the config needs to be commited first?

Could be...I created a workflow in the UI and manually triggered a build, and I still can't get pre-submit to run for this PR. Shall we land this and see what happens? @jonahwilliams

**Comment by jonahwilliams** [comment]
Let me take a look at it real quick

**Comment by jonahwilliams** [comment]
I updated the workflow in the UI to have a separate presubmit workflow (to avoid building)

**Comment by gspencergoog** [comment]
Do we still need this PR?

**Comment by christopherfujino** [comment]
I'll close this, and try land a new one with the new (codemagic) app. I still think it would be improvement to have the CI process be explicitly checked into the source repo.

**Pull request closed without merging**
