### PR TITLE
Added a page is the user says no to consent

### LINKED ISSUE #22: [BUG] Trivial issues around "No" button
Trivial nit: the text says to `Otherwise click "No!"` but the button is "No" with no exclamation mark.

More importantly, once you click No the button turns into another button that says "Did not agree" but that button then does nothing.

Unless you already said that you agreed, then paged back to the second page, then click No, at which point it jumps sideways...

### LINKED ISSUE #31: [FEATURE] Handle case where user does not consent to the terms
**Is your feature request related to a problem? Please describe.**
When the user does not consent to the app's usage terms, there is no additional information provided.

**Describe the solution you'd like**
Implement a new screen that notifies the user that they have not consented and will not be able to use the app. Phrase it much better than that :D

### LINKED ISSUE #86: [BUG] The NO button - it does nothing!
## To Reproduce ##
1. Tap No on the Informed Consent screen

## Expected behavior ##
I'm warned that I cannot participate without accepting, and told to either delete the app or accept the terms.

## Actual behavior ##
There's a red X on the No button, but no other apparent changes.

## Screenshots ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipP1eWxVKAYjXSGJJh3p8hqI0tVVSI3vTV5gKxFG?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

### PR DESCRIPTION
**Pull request by JoseAlba**
Added a page that guides the user to a page where they say no.

Closes #22 
Closes #31 
Closes #86 

The actual content in the page is not displayed. But in order to update the content shown to the user all you have to do is change the file denied_consent.md

Screen Shot 2020-03-23 at 6 41 27 PM

### CODE REVIEW

**Comment by JoseAlba** [comment]
consent_deny

**Comment by appsforartists** [comment]
"The user has denied consent" is not a helpful message.  It sounds like you're talking _about_ the user, not _to_ them.

Can we just delete the "no" button altogether?

**Comment by javierlopez288** [comment]
Screen Shot 2020-03-23 at 5 30 41 PM
Pending content updates, we should do this for now. Please note that we are updating the theme per Phil's new direction

**Comment by JoseAlba** [comment]
updated_specs

Added the updated specs, didn't add the buttons below as adding them would imply a continuous loop instead just added a back button in the appbar

**Comment by HansMuller** [comment]
Did you intend to include ios/Podfile.lock and pubspec.lock in this PR

**Comment by JoseAlba** [comment]
> Did you intend to include ios/Podfile.lock and pubspec.lock in this PR

No, I removed it from the PR

**Review by dnfield — APPROVED** [review]
LGTM

**Comment by dnfield** [comment]
@jonahwilliams @christopherfujino any idea why this one isn't running CI?

**Comment by christopherfujino** [comment]
> @jonahwilliams @christopherfujino any idea why this one isn't running CI?

Pre-submit is not working currently. To enable we will have to re-create the codemagic app. See chat ci-cd channel for context.

**Comment by appsforartists** [comment]
"Did not agree" is weird copy for that button.  "I don't agree" would be better.

**Pull request merged**
