### PR TITLE
[WIP] add codemagic.yaml downloaded directly from web ui

### PR DESCRIPTION
**Pull request by christopherfujino**

### CODE REVIEW

**Comment by jonahwilliams** [comment]
Can you see https://codemagic.io/app/5e78d695d8ea2e0012f6239b/workflow/5e78d695d8ea2e0012f6239a/settings ? the main codemagic app can't do commits to PRs, so I had to setup another. Alternatively I could grab the config for you

**Comment by christopherfujino** [comment]
> Can you see https://codemagic.io/app/5e78d695d8ea2e0012f6239b/workflow/5e78d695d8ea2e0012f6239a/settings ? the main codemagic app can't do commits to PRs, so I had to setup another. Alternatively I could grab the config for you

I cannot see that.

**Comment by christopherfujino** [comment]
@jonahwilliams so I added pre-submit just so I could test this (and it ran on the 5e78d app), and this config passed on everything but "Debug-Beta" (which I'm assuming is expected based on post-submit on develop?). However I can't look at any of the details, as I get a 404 from codemagic.

**Comment by mit-mit** [comment]
This yaml appears to be missing the flutter format check?

**Comment by christopherfujino** [comment]
> This yaml appears to be missing the flutter format check?

Ahh yeah, that must be on the other codemagic app @jonahwilliams referred to.

**Comment by jonahwilliams** [comment]
@christopherfujino could you update this for the right app id and then add branch triggering (for tests only)? I'm not sure if the yaml format is documented anywhere

**Comment by christopherfujino** [comment]
> @christopherfujino could you update this for the right app id and then add branch triggering (for tests only)? I'm not sure if the yaml format is documented anywhere

From what I see https://docs.codemagic.io/building/yaml/, it doesn't look like there's a way to specify the app id. I pushed new commits to this branch, but pre-submit didn't trigger. I will try to open a new PR.

**Pull request closed without merging**
