### PR TITLE
First Screen UI Changes

### LINKED ISSUE #71: First screen isn't actionable
## Context ##
The first screen doesn't give the user enough context to understand what this app is.  The list items look like they could be buttons.

## Suggestions ##
- [ ] Simplify the heading.  "The CovidNearMe App" is a weird name for a product.  Can we just say "Welcome to CovidNearMe."?
- [ ] Add a heading that provides context to the feature list:

    "CovidNearMe is a US Centers for Disease Control project to help the public respond to the novel coronavirus (COVID-19).  It allows you to:"
- [ ] Change the button copy to "Get started"

## Screenshot ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipOUHVbyVSTDUL5frFr9CdHq9fJsgj3w0ppwfN2X?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

### PR DESCRIPTION
**Pull request by aadarsh-patel**
Closes #71 .

I did UI changes on the First Screen accordingly to the helpful suggestion given by the @appsforartists on the Issue's description.

I have also attached before and after images so that it will be easier for the reviewer to review.

### CODE REVIEW

**Comment by aadarsh-patel** [comment]
Many tests are failing.

Looks like i have to make some changes on integration tests and also image for golden test needs to be updated.
Give me some time to fix the above issues.

**Comment by aadarsh-patel** [comment]
Made some wrong choices in this PR. Deleting this branch and will be working on a fresh new branch.

**Comment by ferndot** [comment]
Thanks @aadarsh-patel. @ me when the fresh PR goes up please :)

**Comment by aadarsh-patel** [comment]
Thank you for responding @joshua-s ,
I am on it.

**Pull request closed without merging**
