### PR TITLE
Add an alert dialog if user hasn't enter a temperature or entered an invalid temperature

### LINKED ISSUE #82: Submitting with no temperature doesn't allow you to add one later
## Context ##
If I complete a health checkup without a temperature, it tells me "You have completed your checkup for today!"  

I'm surprised that temperature is a requested field, but there's no way for me to submit it later.  I also wonder what happens if I develop severe symptoms later in the day, after I've already completed the survey.

I don't know if this is intentional (to prevent people from gaming the system by changing their answers until they get a test), but it's an unexpected user experience.

## Screenshot ##
https://photos.google.com/share/AF1QipPNzbQ9YfdnsdI-nSG2WbrB9J5y35_mu5uOORQ4X2pNHiUvaFTdWdgB3X9Y6WxfBw/photo/AF1QipN95cJDwQAv0gthHSkhr39XynMrp25eRJXj1_oI?key=am52QmZoVTZqOWxxWURVVE9EdkJpYUM3LWxfdGlB

## Smartphone: ##
 - Device: Essential
 - OS: Android 10 QP1A.191005.014
 - App version: 6d80da8

### LINKED ISSUE #96: [BUG] UX: subjective page should not select slider values by default.
**Describe the bug**
On the subjective page, by default, the sliders are selected with the lowest value. User might hit continue quickly and miss this page. It might be better to force user select a value.

**To Reproduce**
1. Go to 'home'
1. Click on 'Check up on your health'
1. Click on 'Start checkup'
1. See that the sliders are selected

**Expected behavior**
We should force user to select a value so they don't miss this page.

**Screenshots**
Screen Shot 2020-03-23 at 6 36 27 PM

related to https://github.com/coronavirus-diary/coronavirus-diary/issues/82

### PR DESCRIPTION
**Pull request by cyanglaz**
Fixes https://github.com/coronavirus-diary/coronavirus-diary/issues/82
And potentially makes it easier to fix https://github.com/coronavirus-diary/coronavirus-diary/issues/96

Will add tests if we will go with this approach.

Screen Shot 2020-03-23 at 8 01 55 PM

### CODE REVIEW

**Comment by cyanglaz** [comment]
Just saw this https://github.com/coronavirus-diary/coronavirus-diary/pull/73
Could be related and we might end up needing to update this PR if https://github.com/coronavirus-diary/coronavirus-diary/pull/73 lands

**Comment by dnfield** [comment]
Can you fix up the merge conflicts?

**Comment by cyanglaz** [comment]
@joshua-s based on your comment here: https://github.com/coronavirus-diary/coronavirus-diary/issues/82#issuecomment-604275522
Does it mean we don't need the feature provided in this PR? If so I'll close it.

**Comment by dnfield** [comment]
That comment seems to be about how frequently you can submit, rather than which fields are required.  I think making this a required field makes sense.  @timsneath can you confirm?

**Comment by timsneath** [comment]
I don't know whether this is a required field or not; @joshua-s? 

I'm wondering if there's a viable scenario where someone doesn't have access to an accurate thermometer but wants to enter other fields.

**Comment by cyanglaz** [comment]
Maybe we can change the alert to warn user instead of blocking the flow? They can still submit without a temperature after dismiss the warning dialog.

**Comment by ferndot** [comment]
Hey! @cyanglaz @timsneath apologies for the delay. All fields should be optional in the current world. The goal is to minimize user friction/dropoff and capture partial data vs no data. As Tim mentioned, there can be types of data that a user is not able to answer. There can also be types of data that a user does not wish to provide--we should respect that.

Concerning warning the user instead of blocking the flow, it may be good to consider other UX for warnings that may be a smaller interruption than an alert. One that comes to mind is a snackbar.

**Comment by cyanglaz** [comment]
Snack bar works. Should we ask user the submit again after seeing the snack bar?

**Comment by ferndot** [comment]
@cyanglaz Oh, I see what you mean--this is at the end of the questions. Do you think that a snackbar blocking submission could be confusing to a user?

**Comment by cyanglaz** [comment]
@joshua-s Yeah, I think an alert might suit better in this situation. However, as you mentioned, we shouldn't block the flow. Maybe we can just do a one time alert pop up and the user can still submit without a temperature after they dismiss the alert.

**Comment by ferndot** [comment]
Update on this: the temperature question is going to be moving around (it will be merged in with the subjective questions). It might be good to pause on this PR until that is implemented and then re-investigate how best to nudge the user to complete fields.

**Comment by gspencergoog** [comment]
Also, didn't we make all the questions optional?  In which case this alert wouldn't make sense to show.

**Comment by timsneath** [comment]
Yesterday we discussed making temperature optional and the others required,
and I think that's where we landed.

**Comment by gspencergoog** [comment]
Oh, OK. The PRD still says "All questions should be optional."

**Comment by timsneath** [comment]
Damn. Sorry. @joshua-s

**Comment by ferndot** [comment]
@cyanglaz @gspencergoog @timsneath thanks for your patience: work was quite busy today. My current understanding is that all questions are optional.

The rationale for this is:
1. This will help reduce user friction and dropoff. 
2. There can be types of data that a user is not able to answer.
3. There can be types of data that a user does not wish to provide.

**Comment by joshua-s** [comment]
We can revisit this for sure--and I do apologize if I missed/misunderstood a conversation about this.

**Comment by ferndot** [comment]
I think the argument for keeping things optional is pretty strong. However, we can revisit it if needed--and I do apologize if I missed/misunderstood a conversation about this.

**Comment by dnfield** [comment]
I think the core question is whether we want to tolerate bad data in the backend or not.

The real question is whether that data will still be useful if it is incomplete, and whether the backend can tolerate having the majority of its data be incomplete. 

Checking on the website, it looks like it allows you to submit an incomplete form - not clear to me what this actually does to the backend though.

**Comment by gspencergoog** [comment]
Since the current consensus is that all questions are optional, I'm going to close this PR.  We can reopen, or open an issue if we want to reevaluate that decision.

Currently, in the interest of making things optional, the temperature inputs will accept an invalid temperature, but will turn red, show an error, and not be recorded when submitted.

**Comment by ferndot** [comment]
> The real question is whether that data will still be useful if it is incomplete, and whether the backend can tolerate having the majority of its data be incomplete.

@dnfield for this project, it was decided that a larger volume of incomplete data is better than a reduced volume of complete data. @eethomp has more context on this.

**Pull request closed without merging**
