### PR TITLE
Move Informed Consent to the Symptom Report flow

### LINKED ISSUE #150: [Symptom Report] Move Informed Consent to the Symptom Report flow
Requirements:
- The second step of the Symptom Report should require the user to accept an Informed Consent.
   - This has been provided in [The MVP Questionnaire Doc](https://docs.google.com/document/d/18oaJbmLTKxK3sHRysLY4lePaTQduWsPZY6ZJ1A_VQ2Q/edit?usp=sharing).
      - Omit the block tagged "\<not MVP>".
   - Additional blank lines may be inserted for readability.
   - If the Informed Consent dialog has already been accepted, it should not be shown again.
   - If the Informed Consent is not accepted, the user should be thanked, told they may accept consent at a later time, and be returned to the home screen.
   - If the user has previously rejected consent and returns to the Symptom Report Flow again, they should be provided with another opportunity to accept the consent.

Acceptance criteria:
- [ ] The Informed Consent step has been removed from the tutorial
- [ ] The Informed Consent step has been added as the second step of the Symptom Report flow
  - [ ] The new content has been added from the MVP Questionnaire Doc
  - [ ] If the user has accepted the Informed Consent, this step is skipped
  - [ ] The user cannot continue to the rest of the Symptom Report flow without accepting the Informed Consent.
- [ ] A new screen or popup has been added to the Symptom Report flow that is shown when the user rejects the Informed Consent

### PR DESCRIPTION
**Pull request by ferndot**
Fixes #150 

- Moves the Informed Consent to the Symptom Report flow
- Adds a new controller pattern to the Tutorial and the Symptom Report flows

### CODE REVIEW

**Comment by ferndot** [comment]
Will fix the tests tomorrow

**Comment by gspencergoog** [comment]
Looks good, I like the new controller.  Let me know when the tests are done, and I'll review those.

**Review by gspencergoog — DISMISSED** [review]
LGTM!

**Comment by ferndot** [comment]
@gspencergoog finally fixed the smoke tests!

**Comment by gspencergoog** [comment]
Looks like the iOS build is still failing?  But I can't see the logs.  You might try pushing an empty commit (with `git commit --allow-empty`) to force it to rebuild.

**Comment by ferndot** [comment]
@gspencergoog pushed!

**Pull request merged**
